// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateDevice(ctx context.Context, deviceID string) (Device, error)
	CreateUpdate(ctx context.Context, arg CreateUpdateParams) (Update, error)
	DeleteDevice(ctx context.Context, deviceID string) (Device, error)
	DeleteUpdate(ctx context.Context, version string) (Update, error)
	GetDevice(ctx context.Context, deviceID string) (Device, error)
	GetNextVersion(ctx context.Context, version string) (Update, error)
	GetUpdate(ctx context.Context, version string) (Update, error)
	ListAllDevices(ctx context.Context) ([]ListAllDevicesRow, error)
	ListUpdatesBetweenDates(ctx context.Context, arg ListUpdatesBetweenDatesParams) ([]Update, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
}

var _ Querier = (*Queries)(nil)
